import { StyleSheet } from "react-native";

export const colors = {
  background: "#fbfbfb",
  surface: "#ffffff",
  text: "#111111",
  muted: "#666666",
  faint: "#8f8f8f",
  divider: "#ededed",
  accent: "#dff2ff",
  accentStrong: "#bce7ff",
  selected: "#eff9ff",
  error: "#a84040",
  errorSurface: "#fff1f1",
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { flexGrow: 1, paddingHorizontal: 20, paddingVertical: 28 },
  authContent: { justifyContent: "center", minHeight: "100%" },
  brand: { fontSize: 14, color: colors.muted, marginBottom: 18 },
  title: { fontSize: 30, fontWeight: "700", color: colors.text, marginBottom: 8 },
  subtitle: { fontSize: 15, lineHeight: 23, color: colors.muted, marginBottom: 28 },
  modeSwitch: {
    flexDirection: "row",
    backgroundColor: "#f1f1f1",
    borderRadius: 28,
    padding: 4,
    marginBottom: 24,
  },
  modeButton: { flex: 1, borderRadius: 22, paddingVertical: 11, alignItems: "center" },
  modeButtonActive: { backgroundColor: colors.surface },
  modeText: { color: colors.muted, fontSize: 15, fontWeight: "600" },
  modeTextActive: { color: colors.text },
  field: { marginBottom: 16 },
  label: { color: colors.text, fontSize: 14, fontWeight: "600", marginBottom: 8 },
  input: {
    height: 54,
    paddingHorizontal: 18,
    borderRadius: 27,
    backgroundColor: colors.surface,
    color: colors.text,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  passwordRow: { flexDirection: "row", alignItems: "center", position: "relative" },
  passwordInput: { flex: 1, paddingRight: 70 },
  textAction: { position: "absolute", right: 18, paddingVertical: 8 },
  textActionLabel: { color: colors.muted, fontSize: 13, fontWeight: "600" },
  note: { color: colors.faint, fontSize: 13, lineHeight: 20, marginTop: 2 },
  error: { color: colors.error, backgroundColor: colors.errorSurface, padding: 13, borderRadius: 12, marginBottom: 16, fontSize: 14 },
  primaryButton: { marginTop: 24, height: 56, borderRadius: 28, backgroundColor: colors.accent, justifyContent: "center", alignItems: "center" },
  primaryButtonDisabled: { opacity: 0.55 },
  primaryButtonText: { color: colors.text, fontSize: 16, fontWeight: "700" },
  footer: { color: colors.faint, fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 22 },
  topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 36 },
  topBrand: { color: colors.text, fontSize: 18, fontWeight: "700" },
  avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.accent, justifyContent: "center", alignItems: "center" },
  avatarText: { color: colors.text, fontWeight: "700" },
  hero: { backgroundColor: colors.surface, borderRadius: 24, padding: 22, marginBottom: 20, borderWidth: 1, borderColor: colors.divider },
  eyebrow: { color: colors.muted, fontSize: 13, marginBottom: 9 },
  heroTitle: { color: colors.text, fontSize: 25, fontWeight: "700", lineHeight: 33, marginBottom: 10 },
  heroText: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: "700", marginBottom: 12 },
  previewRow: { backgroundColor: colors.surface, padding: 17, borderBottomWidth: 1, borderColor: colors.divider },
  previewHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  previewTitle: { color: colors.text, fontSize: 16, fontWeight: "600", marginBottom: 5 },
  previewTitleInRow: { flex: 1, minWidth: 0 },
  homeworkStatus: { flexDirection: "row", alignItems: "center", flexShrink: 0, gap: 4, paddingTop: 1 },
  homeworkStatusText: { fontSize: 12, lineHeight: 17, fontWeight: "700" },
  previewText: { color: colors.muted, fontSize: 14 },
  previewTag: { color: colors.faint, fontSize: 12, marginTop: 8 },
  homeworkFooter: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12, marginTop: 8 },
  homeworkAction: { color: colors.faint, fontSize: 12, lineHeight: 17, flex: 1, minWidth: 0 },
  homeworkDispatchDate: { color: colors.faint, fontSize: 12, lineHeight: 17, flexShrink: 0, textAlign: "right" },
  profileCard: { backgroundColor: colors.surface, borderRadius: 18, padding: 20, borderWidth: 1, borderColor: colors.divider },
  profileName: { color: colors.text, fontSize: 21, fontWeight: "700", marginBottom: 8 },
  profilePhone: { color: colors.muted, fontSize: 15 },
  settingsSection: { marginTop: 18, gap: 14 },
  readonlyField: { minHeight: 54, borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.divider, paddingHorizontal: 16, paddingVertical: 12, justifyContent: "center" },
  pointsPanel: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.divider, padding: 16, gap: 12 },
  pointsTopRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between" },
  pointsValue: { color: colors.text, fontSize: 36, lineHeight: 42, fontWeight: "800" },
  pointsLevel: { color: colors.text, fontSize: 20, lineHeight: 30, fontWeight: "700" },
  progressTrack: { height: 10, borderRadius: 5, backgroundColor: "#f1f1f1", overflow: "hidden" },
  progressFill: { height: 10, borderRadius: 5, backgroundColor: colors.accentStrong },
  pointEventList: { borderTopWidth: 1, borderColor: colors.divider, paddingTop: 8, gap: 8 },
  pointEventRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  trendChart: { minHeight: 214, backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.divider, padding: 14, gap: 12 },
  chartLegend: { flexDirection: "row", alignItems: "center", gap: 16 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  voiceLegendDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.accentStrong },
  homeworkLegendDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: "#d7eadb" },
  chartBars: { height: 162, flexDirection: "row", alignItems: "flex-end", gap: 6 },
  chartDay: { flex: 1, minWidth: 0, alignItems: "center", gap: 4 },
  chartBarSlot: { height: 116, flexDirection: "row", alignItems: "flex-end", justifyContent: "center", gap: 3 },
  voiceBar: { width: 8, borderTopLeftRadius: 4, borderTopRightRadius: 4, backgroundColor: colors.accentStrong },
  homeworkBar: { width: 8, borderTopLeftRadius: 4, borderTopRightRadius: 4, backgroundColor: "#d7eadb" },
  chartDate: { color: colors.muted, fontSize: 11, lineHeight: 14 },
  chartValue: { color: colors.faint, fontSize: 11, lineHeight: 14, textAlign: "center" },
  historyRow: { minHeight: 86, flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 13, borderBottomWidth: 1, borderColor: colors.divider },
  historyIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.selected, alignItems: "center", justifyContent: "center" },
  historyTitleRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 8 },
  historyTitleText: { flex: 1, minWidth: 0 },
  historyStatus: { color: colors.muted, fontSize: 12, lineHeight: 18, fontWeight: "700" },
  logoutButton: { marginTop: 22, minHeight: 50, borderRadius: 25, borderWidth: 1, borderColor: colors.divider, justifyContent: "center", alignItems: "center" },
  logoutText: { color: colors.text, fontWeight: "600", fontSize: 15 },
  emptyHomework: { color: colors.muted, fontSize: 15, lineHeight: 22, backgroundColor: colors.surface, padding: 18 },
  loadingScreen: { justifyContent: "center", alignItems: "center" },
  readingHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1, borderColor: colors.divider },
  headerIconButton: { width: 32, height: 32, alignItems: "center", justifyContent: "center" },
  readingTitle: { color: colors.text, fontSize: 16, fontWeight: "700", maxWidth: "65%" },
  chatContent: { padding: 20, gap: 18 },
  chatTeacher: { alignSelf: "flex-start", backgroundColor: colors.surface, borderRadius: 18, padding: 15, maxWidth: "88%" },
  chatTeacherText: { color: colors.text, fontSize: 15, lineHeight: 22 },
  chatMessage: { gap: 8 },
  chatLabel: { color: colors.muted, fontSize: 13 },
  readingCard: { backgroundColor: colors.surface, borderRadius: 18, overflow: "hidden", borderWidth: 1, borderColor: colors.divider },
  cardThumbnail: { width: "100%", height: 180, backgroundColor: "#f1f1f1" },
  readingCardText: { color: colors.text, padding: 14, fontSize: 15, fontWeight: "600" },
  completedBanner: { backgroundColor: colors.selected, borderRadius: 16, padding: 15 },
  completedText: { color: colors.text, fontSize: 14, lineHeight: 21 },
  readingMessage: { color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: "center" },
  pressedState: { opacity: 0.68 },
  modalSafeArea: { flex: 1, backgroundColor: "rgba(0,0,0,0.42)" },
  modalBackdrop: { flex: 1, justifyContent: "center", alignItems: "center", paddingHorizontal: 16, paddingVertical: 24 },
  readingModal: { width: "100%", maxWidth: 520, maxHeight: "92%", backgroundColor: colors.surface, borderRadius: 24, padding: 20 },
  modalScroll: { maxHeight: "100%" },
  modalScrollContent: { gap: 12, paddingBottom: 4 },
  modalTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  cardImage: { width: "100%", height: 300, maxHeight: 340, backgroundColor: "#f1f1f1", borderRadius: 12 },
  modalPage: { color: colors.muted, fontSize: 13, textAlign: "center" },
  statusPill: { alignSelf: "center", paddingHorizontal: 12, paddingVertical: 7, borderRadius: 16 },
  statusUnmade: { backgroundColor: "#f1f1f1" },
  statusDone: { backgroundColor: colors.selected },
  statusGraded: { backgroundColor: "#e8f5e9" },
  statusPillText: { color: colors.text, fontSize: 13, fontWeight: "600" },
  secondaryButton: { minHeight: 48, borderRadius: 24, borderWidth: 1, borderColor: colors.divider, justifyContent: "center", alignItems: "center" },
  secondaryButtonText: { color: colors.text, fontSize: 15, fontWeight: "600" },
  recordButton: { minHeight: 52, borderRadius: 26, backgroundColor: "#f1f1f1", justifyContent: "center", alignItems: "center" },
  recordButtonText: { color: colors.text, fontSize: 15, fontWeight: "700" },
  closeModal: { alignItems: "center", paddingVertical: 7 },
  modalControls: { flexDirection: "row", justifyContent: "center", gap: 12, paddingTop: 2 },
  iconButton: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, borderColor: colors.divider, justifyContent: "center", alignItems: "center" },
  iconButtonRecord: { width: 54, height: 54, borderRadius: 27, backgroundColor: "#f1f1f1", justifyContent: "center", alignItems: "center" },
  iconButtonSubmit: { width: 54, height: 54, borderRadius: 27, backgroundColor: colors.accent, justifyContent: "center", alignItems: "center" },
  nextActionButton: { minHeight: 52, borderRadius: 26, backgroundColor: colors.accent, justifyContent: "center", alignItems: "center" },
  nextHomeworkCard: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.accentStrong, padding: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  nextHomeworkText: { flex: 1, minWidth: 0, paddingRight: 10 },
  recordingHint: { color: colors.muted, fontSize: 13, textAlign: "center" },
  assessmentCompact: { borderTopWidth: 1, borderColor: colors.divider, marginHorizontal: 14, marginTop: 3, paddingTop: 9, paddingBottom: 12 },
  assessmentSummary: { borderTopWidth: 1, borderColor: colors.divider, paddingTop: 11, alignItems: "center", gap: 5 },
  assessmentTitle: { color: colors.muted, fontSize: 13, lineHeight: 19, fontWeight: "600" },
  assessmentMetrics: { color: colors.faint, fontSize: 12, lineHeight: 18 },
  teacherSubmissionCard: { backgroundColor: colors.surface, borderRadius: 14, borderWidth: 1, borderColor: colors.divider, padding: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  teacherAudioButton: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.selected, alignSelf: "center", alignItems: "center", justifyContent: "center" },
  gradePicker: { flexDirection: "row", justifyContent: "center", gap: 10 },
  gradeChoice: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, borderColor: colors.divider, alignItems: "center", justifyContent: "center" },
  gradeChoiceActive: { backgroundColor: colors.accent, borderColor: colors.accentStrong },
  gradeChoiceText: { color: colors.text, fontSize: 16, fontWeight: "700" },
  teacherHeaderActions: { flexDirection: "row", alignItems: "center", gap: 4 },
  headerIconButtonActive: { backgroundColor: colors.selected, borderRadius: 16 },
  teacherPublishContent: { padding: 20, gap: 18 },
  teacherFormSection: { backgroundColor: colors.surface, borderRadius: 14, borderWidth: 1, borderColor: colors.divider, padding: 15, gap: 12 },
  teacherSectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  smallIconButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.selected, alignItems: "center", justifyContent: "center" },
  multilineInput: { height: 96, paddingTop: 14, textAlignVertical: "top" },
  mobileCardDraft: { borderTopWidth: 1, borderColor: colors.divider, paddingTop: 12, gap: 9 },
  mobileCardDraftHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  mobileCardAssetRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  assetIconButton: { width: 40, height: 40, borderRadius: 20, borderWidth: 1, borderColor: colors.divider, alignItems: "center", justifyContent: "center" },
  assetName: { flex: 1, color: colors.muted, fontSize: 14 },
  mobileSegment: { flexDirection: "row", backgroundColor: "#f1f1f1", borderRadius: 24, padding: 4 },
  mobileSegmentOption: { flex: 1, alignItems: "center", paddingVertical: 10, borderRadius: 20 },
  mobileSegmentActive: { backgroundColor: colors.surface },
  mobileNumberRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  mobileNumberInput: { width: 52, height: 40, borderWidth: 1, borderColor: colors.divider, borderRadius: 10, color: colors.text, textAlign: "center" },
  mobileStudentRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 11, borderBottomWidth: 1, borderColor: colors.divider },
  mobileStudentRowActive: { backgroundColor: colors.selected, marginHorizontal: -7, paddingHorizontal: 7, borderRadius: 8 },
  mobilePublishButton: { alignSelf: "center", width: 58, height: 58, borderRadius: 29, backgroundColor: colors.accent, alignItems: "center", justifyContent: "center" },
  practiceHeaderText: { flex: 1, minWidth: 0, alignItems: "center", gap: 2 },
  practiceTemplateLabel: { color: colors.faint, fontSize: 11, lineHeight: 15 },
  practiceCard: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.divider, padding: 18, gap: 10 },
  practiceImage: { width: "100%", height: 170, borderRadius: 12, backgroundColor: "#f1f1f1" },
  practicePrompt: { color: colors.text, fontSize: 22, lineHeight: 31, fontWeight: "700" },
  practiceModalPrompt: { color: colors.text, fontSize: 23, lineHeight: 32, fontWeight: "700", textAlign: "center" },
  objectiveCard: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.divider, padding: 18, gap: 16 },
  objectiveImage: { width: "100%", height: 220, borderRadius: 14, backgroundColor: "#f1f1f1" },
  objectivePrompt: { color: colors.text, fontSize: 22, lineHeight: 31, fontWeight: "700", textAlign: "center" },
  choiceList: { gap: 10 },
  choiceButton: { minHeight: 54, borderRadius: 27, borderWidth: 1, borderColor: colors.divider, backgroundColor: colors.surface, paddingHorizontal: 18, justifyContent: "center", alignItems: "center" },
  choiceButtonActive: { backgroundColor: colors.selected, borderColor: colors.accentStrong },
  choiceText: { color: colors.text, fontSize: 18, lineHeight: 24, fontWeight: "600" },
  scrambleAnswer: { minHeight: 64, borderRadius: 16, borderWidth: 1, borderColor: colors.accentStrong, backgroundColor: colors.selected, padding: 8, flexDirection: "row", flexWrap: "wrap", justifyContent: "center", alignItems: "center", gap: 7 },
  scramblePool: { minHeight: 64, flexDirection: "row", flexWrap: "wrap", justifyContent: "center", alignItems: "center", gap: 7 },
  letterTile: { width: 44, height: 48, borderRadius: 12, borderWidth: 1, borderColor: colors.divider, backgroundColor: colors.surface, justifyContent: "center", alignItems: "center" },
  letterTileActive: { width: 44, height: 48, borderRadius: 12, backgroundColor: colors.accent, justifyContent: "center", alignItems: "center" },
  letterTileText: { color: colors.text, fontSize: 20, fontWeight: "700", textTransform: "uppercase" },
  teacherSubmissionText: { flex: 1, minWidth: 0, paddingRight: 12 },
  templateGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  templateOption: { minHeight: 42, borderRadius: 21, borderWidth: 1, borderColor: colors.divider, paddingHorizontal: 14, justifyContent: "center", alignItems: "center" },
  templateOptionActive: { backgroundColor: colors.accent, borderColor: colors.accentStrong },
  templateOptionText: { color: colors.muted, fontSize: 14, fontWeight: "600" },
  templateOptionTextActive: { color: colors.text },
  learningHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 26 },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  statCard: { flexBasis: "47%", flexGrow: 1, minHeight: 104, borderRadius: 16, borderWidth: 1, borderColor: colors.divider, backgroundColor: colors.surface, padding: 15, justifyContent: "space-between" },
  statValue: { color: colors.text, fontSize: 30, lineHeight: 36, fontWeight: "700" },
  statDuration: { color: colors.text, fontSize: 20, lineHeight: 27, fontWeight: "700" },
  statLabel: { color: colors.muted, fontSize: 13, lineHeight: 18, fontWeight: "600" },
  checkinList: { marginTop: 18, backgroundColor: colors.surface, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.divider },
  checkinRow: { minHeight: 76, flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 11, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: colors.divider },
  checkinDateBadge: { width: 48, height: 52, borderRadius: 12, backgroundColor: colors.selected, alignItems: "center", justifyContent: "center" },
  checkinDay: { color: colors.text, fontSize: 19, lineHeight: 22, fontWeight: "700" },
  checkinMonth: { color: colors.muted, fontSize: 11, lineHeight: 14 },
  checkinDetails: { flex: 1, minWidth: 0 },
});
